### PR TITLE
update event mappings, allow airdate with ms and add new section setting

### PR DESCRIPTION
**Pull request by kdaswani**
**What does this PR do?**
Nielsen has requested we make the following changes to event mappings:

- Update mapping for Video Playback Interrupted to call `stop` instead of `end`
- Add mapping for Video Playback Exited to call `stop`. Context: Fox has requested a new event for Video Playback Exited be added to our spec. This has been approved by the spec committee. See here: https://paper.dropbox.com/doc/Video-Spec-Event-Proposal-for-Video-Playback-Exited--A8j5DFZuVoZYlsG~ZQr96tlcAg-rUDm4tQEB1RsdH0R7Xujm. 
- Update airdate formatter to detect ISO timestamp with milliseconds and format to meet Nielsen's spec
- Update mapping for Video Playback Started to call `play` and load content metadata
- Add UI setting for "Custom Screen/Page Section Property Name" to allow customers to use a different property as the screen section sent to Nielsen. New mapping first checks for this setting and then if it doesn't exist, fallback on screen name. UI setting added to partner portal in `app.segment.build` as `customSectionProperty`.

**Testing**
Unit tests are erroring out with the following message:

`org.mockito.exceptions.base.MockitoException:`
`Mockito cannot mock this class: class com.nielsen.app.sdk.AppSdk.`

Screen Shot 2021-02-11 at 6 14 37 PM

This error happens on the `master` branch as well so I wonder if the Nielsen AppSdk is a private and/or final class. Working on resolving unit tests and testing locally.

Changes being made for iOS and web as well. iOS PR here: https://github.com/segment-integrations/analytics-ios-integration-nielsen-dcr/pull/25

### CODE REVIEW

**Review by migs647 — APPROVED** [review]

**Comment by kdaswani** [comment]
All unit tests passed:

Screen Shot 2021-03-16 at 1 33 55 PM

Had to make a few updates to the integration code and unit tests:
- `Video Playback Exited` (new event) and `Video Playback Completed` were not included in the track handler. I added them both. There was also no unit test for `Video Playback Completed` which is probably why this wasn't caught sooner. I added a test for this and it passed.
- I also updated an existing test to use a long date with milliseconds and lowercase `t` and `z` to check this change. I had already added something similar for uppercase `t` and `z`. Both passed.
- I needed to make a small change to the screen handler to preface `properties().getString(settings.customSectionProperty);` with `screen.` to pull from the payload. The test that references this new setting passed.

I updated the build.gradle to add dependencies to make the unit tests work. For future reference, steps to make unit tests pass:
- Updated and added dependencies in build.gradle (committed here)
- Run gradle task test OR locally change the run configuration by adding -noverify. See this PR comment for more details: https://github.com/segment-integrations/analytics-android-integration-nielsen-dtvr/pull/6#issuecomment-797820882

@migs647 I'm working on local testing, but can you take another look at my most recent commits/changes? Thanks!

**Comment by kdaswani** [comment]
Local testing looks good except for the change allowing for a custom mapping to the `screen` section name. Results below:

Triggered `Video Playback Started` and Video Playback Interrupted`. Corresponding Nielsen calls: PLAY and LOAD METADATA upon playhead start, playhead timer increments by 1, and STOP upon playback interrupted (this was previously END):
Screen Shot 2021-03-22 at 4 43 21 PM

Triggered `Video Playback Started` with an `airdate` property and Video Playback Exited`. Corresponding Nielsen calls: PLAY and LOAD METADATA upon playhead start, playhead timer increments by 1, and STOP upon playback exit (this is a net new event with no calls to Nielsen previously). The `airdate` is an ISO timestamp with milliseconds and is formatted correctly. It is successfully passed to Nielsen; previously airdates with milliseconds were getting dropped:
Screen Shot 2021-03-22 at 4 50 18 PM

The change that is **not** working is the UI setting for "Custom Screen/Page Section Property Name" to allow customers to use a different property as the screen name sent to Nielsen. The new mapping first checks for this setting and then if it doesn't exist, fallback on screen name: https://github.com/segment-integrations/analytics-android-integration-nielsen-dcr/blob/6fa31718eb047edd5c0cc0d64b4b96d7c26bdfad/src/main/java/com/segment/analytics/android/integrations/nielsendcr/NielsenDCRIntegration.java#L599. We added the UI setting to Partner Portal in app.segment.build as `customSectionProperty` and I've configured this to be `test_section_property` in my staging workspace:
Screen Shot 2021-03-22 at 5 20 58 PM

However, when I trigger a `screen` call with the `test_section_property` it is not mapped. It continues to use the screen `name`. My unit tests above passed so I can't seem to figure out why the local test isn't. I confirmed the correct projectSettings are being referenced:
Screen Shot 2021-03-22 at 8 19 50 PM

@migs647 @prayansh do you see anything wrong with my code that would cause this setting to not be picked up? Once this can be resolved, I will pass the integration snapshot to Fox for testing.

For referenc, the following must be added to the app's build.gradle to target the snapshot:

``repositories {
    // add sonatype repository
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
dependencies {
    implementation 'com.segment.analytics.android.integrations:nielsen-dcr:1.3.1-SNAPSHOT'
}

**Comment by kdaswani** [comment]
I have asked Fox to hold off on testing this PR as we work to merge this more urgent PR first: https://github.com/segment-integrations/analytics-android-integration-nielsen-dcr/pull/20. Once we merge and release a new version with PRs changes, I will update this PR so it references the latest master and then work with @pooyaj to generate a new snapshot that I can share with Fox. Thanks!

**Comment by kdaswani** [comment]
Unit tests + CircleCI pass with latest changes!
Screen Shot 2021-03-31 at 12 14 16 PM

**Pull request merged**
